### PR TITLE
fix: explicitly @inject default param, fixes #206

### LINKED ISSUE #206: Extension not working against staging (when using TRANSPILE_ONLY)
- [x] Resolve issues with staging (likely cloudflare access related)

### PR DESCRIPTION
**Pull request by sublimator**

### CODE REVIEW

File: packages/coil-client/src/graphQlClient.ts [hunk 1]
```diff
@@ -29,6 +29,7 @@ export class GraphQlClient {
   public whoAmI = whoAmI
 
   public constructor(
+    @inject(GraphQlClientOptions)
```
Comment (sublimator) [inline packages/coil-client/src/graphQlClient.ts]: This also fixes:
```
  public constructor(
    // @inject(GraphQlClientOptions)
    private config: GraphQlClientOptions//  = new GraphQlClientOptions()
  ) {
```
It's something to do with the default value
